# Generated by Django 3.1.7 on 2025-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20250219_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
