# Generated by Django 3.1.7 on 2025-04-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
