# Generated by Django 3.1.7 on 2025-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20250419_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_language',
            field=models.CharField(choices=[('es', 'Spanish'), ('eus', 'Basque'), ('en', 'English')], default='es', max_length=3),
        ),
    ]
