# Generated by Django 4.2.20 on 2025-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_user_default_language'),
        ('models', '0014_alter_accountactivatetoken_id_alter_friendrequest_id_and_more'),
    ]

    operations = [
    ]
