# Generated by Django 4.2.20 on 2025-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_merge_20250501_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ft_user',
            field=models.BooleanField(default=False),
        ),
    ]
